---
class: 4
flags: 0x0000
unid: OFB6E443ADC408E49F-ON00727D1B852583E7
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: ".settings/.jsdtscope"
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $Revisions
    type: time
    data: "2019-04-25T16:50:31.36-04:00"
    dst: true
  - name: $TITLE
    type: text
    data: ".settings/.jsdtscope"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []