---
class: 4
flags: 0x0000
unid: OF6FB0F32237A6380E-ON00727CE0852583E7
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: ".classpath"
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $Revisions
    type: time
    data: "2019-04-25T16:50:30.77-04:00"
    dst: true
  - name: $TITLE
    type: text
    data: ".classpath"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []