---
ACL:
  opaque: |
    Q0ECAAYCCgAAAAAABQAoABAAeACYAAEAAAAoAAQAAAAEBCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    tgAAAN4BAAAAAAAAwAEAAAAA4AAAAJoBUgEAAAAAAAAAAEVBAgAAAAAAAAAAAAAABQIJAC1EZWZhdWx0
    LQAAAEVBAAAAAAAAAAAAAAAARxAUAFtPdGhlckRvbWFpblNlcnZlcnNdACAIAUVBBgAAAAAAAAAAAAAA
    +AcTAFtMb2NhbERvbWFpbkFkbWluc10AKAFFQQMAAAAAAAAAAAAAAAACCwBbLURlZmF1bHQtXQAAAEVB
    BgAAAAAAAAAAAAAA2gcUAFtMb2NhbERvbWFpblNlcnZlcnNdAAAAAEVBAAAAAAAAAAAAAAAABRALAFtB
    bm9ueW1vdXNdAAAARUEGAAAAAAAAAAAAAADaBxIATG9jYWxEb21haW5TZXJ2ZXJzAGdyAUVBBgAAAAAA
    AAAAAAAA+AcRAExvY2FsRG9tYWluQWRtaW5zAAAARUEAAAAAAAAAAAAAAAAEEAkAQW5vbnltb3VzAAAA
    RUEAAAAAAAAAAAAAAABGEBIAT3RoZXJEb21haW5TZXJ2ZXJzAG8=
DBOptions: 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0